---
- hosts: 'masters'
  become: yes

  tasks:
          - name: Open required ports
            community.general.ufw:
                    rule: allow
                    port: '6443'
                    port: '10250'
                    port: '10257'
                    port: '10259'
                    proto: tcp
                    direction: in

          - name: Open required ports(2)
            community.general.ufw:
                    rule: allow
                    port: 2379:2380
                    proto: tcp
                    direction: in

- hosts: 'workers'
  become: yes

  tasks:
          - name: Open worker ports
            community.general.ufw:
                    rule: allow
                    port: '10250'
                    proto: tcp
                    direction: in


          - name: Open worker ports(2)
            community.general.ufw:
                    rule: allow
                    port: 30000:32767
                    proto: tcp
                    direction: in

- hosts: 'masters, workers'
  become: yes

  tasks:
          - name: Changing Docker to systemd driver
            copy:
                    dest: "/etc/docker/daemon.json"
                    content: |
                            {
                            "exec-opts": ["native.cgroupdriver=systemd"]
                            }

          - name: Disable swap
            shell: |
                    sudo swapoff -a
                    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

          - name: Install Kubernetes required packages
            ansible.builtin.apt:
                    pkg:
                            - apt-transport-https
                            - ca-certificates
                            - curl

          - name: Add Kubernetes apt-key
            ansible.builtin.apt_key:
                    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
                    state: present

          - name: Add Kubernetes repo
            ansible.builtin.apt_repository:
                    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
                    state: present
                    filename: 'kubernetes'

          - name: Install kubelet
            ansible.builtin.apt:
                    name: "kubelet={{  kubelet_version  }}"
                    state: present
                    update_cache: true

          - name: Install kubeadm
            ansible.builtin.apt:
                    name: "kubeadm={{  kubeadm_version  }}"
                    state: present
                    update_cache: true

          - name: Disable automatically upgrading of Kubernetes tools
            shell: |
                    sudo apt-mark hold kubelet kubeadm kubectl

- hosts: 'masters'
  become: yes

  tasks:
          - name: Install kubectl
            ansible.builtin.apt:
                    name: "kubectl={{  kubectl_verison  }}"
                    state: present
                    update_cache: true
